
DESDE amazoncorretto:17-alpine-jdk

COPIAR target/portfolioFullStack-0.0.1-SNAPSHOT.jar portfolioFullStack-0.0.1-SNAPSHOT.jar

PUNTO DE ENTRADA [ "java" , "-jar" , "/portfolioFullStack-0.0.1-SNAPSHOT.jar" ]
